name: foreximf
description: a project test foreximf

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  web_socket_channel: ^2.4.0
  intl: ^0.17.0
  get: ^4.6.5
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^1.3.2
  firebase_core: ^2.1.1
  firebase_crashlytics: ^3.0.3
  firebase_analytics: ^10.0.3
  built_value: ^8.0.0  
  dio: ^4.0.6
  enum_to_string: ^2.0.1
  flutter_config: ^2.0.0
  hexcolor: ^2.0.7
  panara_dialogs: ^0.1.2
  loading_animation_widget: ^1.2.0+3
  sprintf: ^7.0.0
  fancy_shimmer_image: ^2.0.2
  loader_skeleton: ^0.0.4
  fade_shimmer: ^2.0.1
  webviewx: ^0.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  built_value_generator: ^8.0.0
  flutter_lints: ^2.0.0
  package_rename: ^1.2.0



flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/
    - .env.dev
    - .env.prod


  fonts:  
    - family: Rubik
      fonts:
        # ! Light
        - asset: assets/fonts/rubik/Rubik-Light.ttf
          weight: 100
        - asset: assets/fonts/rubik/Rubik-LightItalic.ttf
          weight: 100
          style: italic
        # ! Reguler
        - asset: assets/fonts/rubik/Rubik-Regular.ttf
          weight: 200
        - asset: assets/fonts/rubik/Rubik-Italic.ttf
          weight: 200
          style: italic
        # ! Medium
        - asset: assets/fonts/rubik/Rubik-Medium.ttf
          weight: 300
        - asset: assets/fonts/rubik/Rubik-MediumItalic.ttf
          weight: 300
          style: italic
        # ! Semi Bold
        - asset: assets/fonts/rubik/Rubik-SemiBold.ttf
          weight: 400
        - asset: assets/fonts/rubik/Rubik-SemiBoldItalic.ttf
          weight: 400
          style: italic
        # ! Bold
        - asset: assets/fonts/rubik/Rubik-Bold.ttf
          weight: 500
        - asset: assets/fonts/rubik/Rubik-BoldItalic.ttf
          weight: 500
          style: italic
        # ! Extra Bold
        - asset: assets/fonts/rubik/Rubik-ExtraBold.ttf
          weight: 600
        - asset: assets/fonts/rubik/Rubik-ExtraBoldItalic.ttf
          weight: 600
          style: italic
        # ! Black
        - asset: assets/fonts/rubik/Rubik-Black.ttf
          weight: 700
        - asset: assets/fonts/rubik/Rubik-BlackItalic.ttf
          weight: 700
          style: italic


flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash.png
  android_disable_fullscreen: true
  # flutter pub run flutter_native_splash:create

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: assets/images/logo.png
  # flutter pub run flutter_launcher_icons:main


package_rename_config:
  android:
    app_name: FOREXimf
    package_name: com.pujandan.foreximf
    override_old_package: com.pujandan.foreximf
    lang: kotlin

  ios:
    app_name: FOREXimf
    bundle_name: foreximf
    package_name: com.pujandan.foreximf

  web:
    app_name: FOREXimf
    description: FOREXimf.

  linux:
    app_name: FOREXimf
    package_name: com.pujandan.foreximf
    exe_name: foreximf-linux-x64

  windows:
    app_name: FOREXimf
    organization: PujanDan
    copyright_notice: Copyright ©️ 2022 PujanDan. All rights reserved.
    exe_name: foreximf-win32

  macos:
    app_name: FOREXimf
    package_name: com.pujandan.foreximf
    copyright_notice: Copyright ©️ 2022 PujanDan. All rights reserved.

# flutter pub run package_rename:set